# Generated by Django 5.0.1 on 2024-03-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={},
        ),
    ]
