# Generated by Django 5.0.1 on 2024-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_payment'),
        ('leave_management', '0002_alter_leavetype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesummary',
            name='employee',
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='employee',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
