# Generated by Django 5.0.1 on 2024-03-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment',
            field=models.IntegerField(max_length=140, null=True),
        ),
    ]
