# Generated by Django 5.0.1 on 2024-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_payment'),
        ('projectmanager', '0005_remove_projmanager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ManyToManyField(to='projectmanager.projmanager'),
        ),
    ]
