# Generated by Django 5.0.1 on 2024-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='projects', to='projectmanager.projmanager'),
        ),
    ]
