# Generated by Django 5.0.1 on 2024-03-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='assigned_to',
        ),
    ]
