# Generated by Django 5.0.1 on 2024-03-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_alter_projmanager_employees'),
        ('projects', '0003_rename_created_by_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(to='projectmanager.projmanager'),
        ),
    ]
