# Generated by Django 5.0.1 on 2024-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_alter_projmanager_employees'),
        ('projects', '0004_alter_project_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='projects', to='projectmanager.projmanager'),
        ),
    ]
