# Generated by Django 5.0.1 on 2024-03-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_salary_alter_employee_id'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmanager',
            name='manager_id',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
    ]
