# Generated by Django 5.0.1 on 2024-03-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_projmanager_manager_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projmanager',
            old_name='manager_id',
            new_name='manager_ji',
        ),
    ]
