# Generated by Django 5.0.1 on 2024-03-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_payment'),
        ('projectmanager', '0003_rename_manager_id_projmanager_manager_ji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projmanager',
            name='manager_ji',
        ),
        migrations.AddField(
            model_name='projmanager',
            name='employees',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
