# Generated by Django 5.0.1 on 2024-03-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_remove_projmanager_manager_ji_projmanager_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projmanager',
            name='employees',
        ),
    ]
