# Generated by Django 5.0.1 on 2024-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_manager'),
        ('projectmanager', '0005_remove_projmanager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmanager',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='employees.employee'),
        ),
    ]
