# Generated by Django 5.0.1 on 2024-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_projmanager_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmanager',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
