# Generated by Django 5.0.1 on 2024-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_manager'),
        ('projectmanager', '0007_alter_projmanager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmanager',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.employee'),
        ),
    ]
