# Generated by Django 5.0.1 on 2024-03-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaveapplication', verbose_name='Leave Application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Leave Notification',
                'verbose_name_plural': 'Leave Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
